using System.Collections.Generic;
using UnityEngine;

namespace PoBox
{
    /// <summary>
    /// Joint-stress heatmap: a glow at every joint pivot whose brightness and
    /// size track how hard that joint's motor is working. A fighter about to go
    /// down strains visibly through one ankle before anything else moves, which
    /// is the tell a spectator can otherwise never see — and the same picture
    /// that says whether a policy is fighting its own body.
    ///
    /// IT NEVER TOUCHES A FIGHTER'S OWN MATERIALS, AND THAT IS A RULE, NOT A
    /// SHORTCUT. Colour is identity in this project: red means "no brain,
    /// hand-written", green means "the standard policy on the standard body"
    /// (AGENTS.md). Tinting a limb by stress would overwrite the one thing the
    /// audience is meant to read off a fighter's body, and washing a
    /// MaterialPropertyBlock over the renderers would additionally fight the
    /// copy wash <see cref="Systems_ContestSpawner"/> applies to duplicates. So
    /// the heatmap is drawn as separate additive geometry through
    /// Graphics.RenderMesh — no GameObjects, no renderers, nothing that can
    /// outlive the frame — and the ramp deliberately avoids saturated red and
    /// green, running deep blue to amber to white-hot instead.
    ///
    /// Created at runtime by <see cref="Systems_ContestSpawner"/>; self-
    /// discovers fighters in Start like every other presentation system.
    /// Test-scene harness only — training scenes carry no cameras and would
    /// pay for this for nothing.
    /// </summary>
    public sealed class Systems_JointStressView : MonoBehaviour
    {
        /// <summary>
        /// Below this fraction of a joint's motor limit nothing is drawn at
        /// all. A standing fighter's fourteen joints are mostly idle, so this
        /// is what keeps a typical frame at a handful of draws rather than
        /// eight fighters times fourteen.
        /// </summary>
        private const float VISIBLE_LOAD = 0.12f;

        /// <summary>
        /// Smoothing rate for the displayed load, per second. The raw proxy is
        /// min(maxForce, spring x |w|) sampled off angular velocity, which is
        /// noisy at 50 Hz — unsmoothed it strobes and reads as sparkle rather
        /// than as effort.
        /// </summary>
        private const float SMOOTH_RATE = 8f;

        /// <summary>Glow diameter in metres at zero load and at saturation.</summary>
        private const float MIN_DIAMETER = 0.06f;
        private const float MAX_DIAMETER = 0.19f;

        // Deep blue -> amber -> white-hot. Never the identity red or green: see
        // the class comment.
        private static readonly Color CoolColor = new(0.15f, 0.45f, 1f, 1f);
        private static readonly Color WarmColor = new(1f, 0.62f, 0.12f, 1f);
        private static readonly Color HotColor = new(1f, 0.97f, 0.88f, 1f);

        private static readonly int BaseColorId = Shader.PropertyToID("_BaseColor");
        private static readonly int ColorId = Shader.PropertyToID("_Color");

        private Systems_FighterRig[] _rigs;
        private float[][] _smoothedLoads;
        private Material _material;
        private Mesh _mesh;
        /// <summary>
        /// One property block PER GLOW PER FRAME, not one reused for all of
        /// them. <see cref="RenderParams"/> holds a REFERENCE to its matProps,
        /// and the draws it queues are not submitted until the frame renders —
        /// so a single block rewritten between calls is a race whose visible
        /// result would be every glow in the ring taking the colour of the last
        /// one written. Pooled and grown once rather than allocated per draw.
        /// </summary>
        private readonly List<MaterialPropertyBlock> _blocks = new();
        private int _blocksUsed;
        private bool _ready;

        /// <summary>
        /// Turns the overlay off without destroying it, for a HUD toggle or a
        /// clean winner tableau.
        /// </summary>
        public bool ShowStress { get; set; } = true;

        private void Start()
        {
            _rigs = FindObjectsByType<Systems_FighterRig>(FindObjectsSortMode.InstanceID);
            if (_rigs.Length == 0)
            {
                return;
            }

            Systems_SpectatorKit kit = Systems_SpectatorKit.Load();
            _material = kit != null ? kit.overlayMaterial : null;
            if (_material == null)
            {
                // Not an error. The kit is generated by Tools/ML Boxing/17 and a
                // project that has never run it should lose the overlay, not the
                // contest.
                Debug.LogWarning("Systems_JointStressView: no SpectatorKit overlay material — " +
                                 "joint-stress heatmap disabled. Run Tools/ML Boxing/17.");
                return;
            }

            _mesh = BuildSphereMesh();
            if (_mesh == null)
            {
                return;
            }

            _smoothedLoads = new float[_rigs.Length][];
            for (int rigIndex = 0; rigIndex < _rigs.Length; rigIndex++)
            {
                _smoothedLoads[rigIndex] = new float[_rigs[rigIndex].Joints.Count];
            }

            _ready = true;
        }

        private void OnDestroy()
        {
            // Built here, so destroyed here — a mesh created from a primitive
            // is not owned by any asset and leaks across play sessions in the
            // editor otherwise.
            if (_mesh != null)
            {
                Destroy(_mesh);
            }
        }

        /// <summary>
        /// LateUpdate, not FixedUpdate: this draws for one frame and the pose it
        /// draws against is the one the renderer is about to use. Smoothing is
        /// handed unscaled delta time so the overlay keeps living through the
        /// round countdown's timeScale 0 and the knockout slow-mo, like every
        /// other presentation system here.
        /// </summary>
        private void LateUpdate()
        {
            if (!_ready || !ShowStress)
            {
                return;
            }

            float dt = Time.unscaledDeltaTime;
            _blocksUsed = 0;
            for (int rigIndex = 0; rigIndex < _rigs.Length; rigIndex++)
            {
                Systems_FighterRig rig = _rigs[rigIndex];
                if (rig == null)
                {
                    continue;
                }
                var joints = rig.Joints;
                float springScale = rig.CurrentSpringScale;
                float[] smoothed = _smoothedLoads[rigIndex];

                for (int jointIndex = 0; jointIndex < joints.Count && jointIndex < smoothed.Length; jointIndex++)
                {
                    RigJointEntry entry = joints[jointIndex];
                    if (entry == null || entry.body == null)
                    {
                        continue;
                    }
                    // One definition of "working hard", shared with the thing
                    // that drains stamina from it.
                    float load = Systems_Stamina.JointLoad01(entry, springScale);
                    smoothed[jointIndex] = Mathf.Lerp(smoothed[jointIndex], load, dt * SMOOTH_RATE);
                    float shown = smoothed[jointIndex];
                    if (shown < VISIBLE_LOAD)
                    {
                        continue;
                    }
                    DrawGlow(JointPivot(entry), shown);
                }
            }
        }

        /// <summary>
        /// Where the articulation actually is. The joint's anchor is expressed
        /// in the jointed body's local space, so this is the hip, knee or ankle
        /// itself rather than the centre of the thigh or shin the motor drives —
        /// a glow floating in the middle of a limb reads as a wound, not as a
        /// joint under load.
        /// </summary>
        private static Vector3 JointPivot(RigJointEntry entry)
        {
            if (entry.joint != null)
            {
                return entry.joint.transform.TransformPoint(entry.joint.anchor);
            }
            return entry.body.worldCenterOfMass;
        }

        private void DrawGlow(Vector3 position, float load01)
        {
            float clamped = Mathf.Clamp01(load01);
            // Two-leg ramp: the first half climbs out of the blue into amber,
            // the second washes to white. A single Lerp from blue to white
            // passes through grey in the middle, which is exactly the band a
            // fighter spends most of its time in.
            Color color = clamped < 0.5f
                ? Color.Lerp(CoolColor, WarmColor, clamped * 2f)
                : Color.Lerp(WarmColor, HotColor, (clamped - 0.5f) * 2f);
            // Additive, so alpha is brightness rather than coverage: a quiet
            // joint fades out instead of hanging around as a grey ball.
            color.a = Mathf.Clamp01((clamped - VISIBLE_LOAD) / (1f - VISIBLE_LOAD));
            color *= color.a;
            color.a = 1f;

            MaterialPropertyBlock block = NextBlock();
            block.SetColor(BaseColorId, color);
            block.SetColor(ColorId, color);

            var renderParams = new RenderParams(_material)
            {
                // Overlays are presentation only: they must never occlude a
                // fighter for a shadow map or a depth prepass, and nothing in
                // the scene should light them.
                shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off,
                receiveShadows = false,
                matProps = block
            };

            float diameter = Mathf.Lerp(MIN_DIAMETER, MAX_DIAMETER, clamped);
            Graphics.RenderMesh(
                renderParams, _mesh, 0,
                Matrix4x4.TRS(position, Quaternion.identity, Vector3.one * diameter));
        }

        /// <summary>
        /// The next unused property block this frame, allocating one only the
        /// first time that many glows are drawn at once. Steady state is zero
        /// allocations.
        /// </summary>
        private MaterialPropertyBlock NextBlock()
        {
            if (_blocksUsed == _blocks.Count)
            {
                _blocks.Add(new MaterialPropertyBlock());
            }
            return _blocks[_blocksUsed++];
        }

        /// <summary>
        /// A unit sphere, taken from a primitive and kept.
        ///
        /// Resources.GetBuiltinResource is the obvious way to ask for one and is
        /// not reliable across render pipelines and versions; creating a
        /// primitive and stealing its mesh is. The GameObject is destroyed
        /// immediately — only the mesh is wanted, and the collider a primitive
        /// brings with it would otherwise sit in the ring and be hit by
        /// fighters.
        /// </summary>
        private static Mesh BuildSphereMesh()
        {
            var primitive = GameObject.CreatePrimitive(PrimitiveType.Sphere);
            var filter = primitive.GetComponent<MeshFilter>();
            Mesh source = filter != null ? filter.sharedMesh : null;
            Mesh copy = source != null ? Instantiate(source) : null;
            if (copy != null)
            {
                copy.name = "JointStressGlow";
            }
            Destroy(primitive);
            return copy;
        }
    }
}
