using System.Collections.Generic;
using UnityEngine;

namespace PoBox
{
    /// <summary>
    /// A soft dark disc under every fighter.
    ///
    /// WHY, AND WHY IT IS NOT A REAL SHADOW. Real shadows are what tell a viewer
    /// a body is standing ON something rather than floating over it, and on a
    /// phone this project cannot afford many: the mobile pipeline asset runs one
    /// shadow cascade at 1024 and has additional-light shadows switched OFF
    /// entirely, so the four spot lights over the ring cast nothing at all there
    /// — they cost per-pixel shading and return no grounding cue. Meanwhile a
    /// contest with Nick in it runs at about 20 fps, which is the project's open
    /// item, so the answer cannot be "turn more shadows on".
    ///
    /// A blob is the trade every fighting game makes: one unlit quad per
    /// fighter, no shadow map, no extra pass, drawn in a handful of
    /// microseconds, and it delivers the one thing the expensive version was
    /// being asked for — contact. It works under the main light's real shadow
    /// rather than instead of it: the key light still casts, and this fills in
    /// the contact point the single low-resolution cascade smears away.
    ///
    /// IT READS THE FOOT, NOT THE PELVIS. Height above ground scales the disc
    /// wider and fainter, so a fighter lifting a leg loses contact visibly and a
    /// fighter in the air has almost none — which is the walk race's whole
    /// subject rendered as a shadow. Taken from the LOWER of the two feet,
    /// because that is the one in contact, and from the ground the rig itself
    /// probed (GroundY) so the 1 m ring platform needs no special case.
    ///
    /// DRAWN, NOT INSTANTIATED. Graphics.RenderMesh rather than a GameObject per
    /// fighter: no transforms to keep in sync, nothing to clean up when a
    /// contest ends, and no scene carries one. Same approach, and the same
    /// property-block pooling requirement, as
    /// <see cref="Systems_JointStressView"/>.
    ///
    /// Created at runtime by <see cref="Systems_ContestSpawner"/>. Test-scene
    /// harness only.
    /// </summary>
    public sealed class Systems_BlobShadow : MonoBehaviour
    {
        /// <summary>Disc radius directly under a planted foot, in metres.</summary>
        private const float BASE_RADIUS = 0.42f;

        /// <summary>
        /// Height at which the disc has faded out completely. A fighter whose
        /// lowest foot is this far up is airborne by any reading.
        /// </summary>
        private const float FADE_HEIGHT = 1.1f;

        /// <summary>How much wider the disc gets across the full fade height.</summary>
        private const float SPREAD_AT_FADE = 2.2f;

        /// <summary>
        /// Opacity of the disc at full contact. Alpha blended rather than
        /// multiplied: a multiply can only ever darken by the amount baked into
        /// its texture, so the disc could not fade out as a foot lifts — which
        /// is the one thing this has to do.
        /// </summary>
        private const float CONTACT_ALPHA = 0.55f;

        /// <summary>
        /// Lift off the ground plane. Large enough to beat depth fighting with
        /// the canvas at the ranges the drama camera works at, small enough that
        /// the disc never visibly floats.
        /// </summary>
        private const float GROUND_OFFSET = 0.012f;

        private Systems_FighterRig[] _rigs;
        private Material _material;
        private Mesh _quad;
        private readonly List<MaterialPropertyBlock> _blocks = new();
        private int _blocksUsed;
        private bool _ready;

        private static readonly int BaseColorId = Shader.PropertyToID("_BaseColor");

        private void Start()
        {
            _rigs = FindObjectsByType<Systems_FighterRig>(FindObjectsSortMode.InstanceID);
            if (_rigs.Length == 0)
            {
                return;
            }

            Systems_SpectatorKit kit = Systems_SpectatorKit.Load();
            _material = kit != null ? kit.blobShadowMaterial : null;
            if (_material == null)
            {
                // Not an error, for the same reason the joint-stress overlay's
                // absence is not: the kit is generated by
                // PoBox/Scene/Build Spectator Kit, and a project that has never
                // run it should lose the blobs rather than the contest.
                Debug.LogWarning("Systems_BlobShadow: no blob material in the spectator kit — " +
                                 "contact shadows disabled. Run PoBox/Scene/Build Spectator Kit.");
                return;
            }

            _quad = BuildQuad();
            _ready = _quad != null;
        }

        private void OnDestroy()
        {
            // Built here, so destroyed here. A mesh made from code is owned by
            // no asset and leaks across play sessions in the editor otherwise —
            // the lesson Systems_JointStressView's sphere already records.
            if (_quad != null)
            {
                Destroy(_quad);
            }
        }

        private void LateUpdate()
        {
            if (!_ready)
            {
                return;
            }
            _blocksUsed = 0;
            var renderParams = new RenderParams(_material)
            {
                // Shadows off in both directions: a shadow that casts a shadow
                // is a bug, and one that receives the key light's own shadow
                // would double-darken exactly where it is already darkest.
                shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off,
                receiveShadows = false
            };

            for (int rigIndex = 0; rigIndex < _rigs.Length; rigIndex++)
            {
                Systems_FighterRig rig = _rigs[rigIndex];
                if (rig == null || rig.Pelvis == null)
                {
                    continue;
                }

                float groundY = rig.GroundY;
                float height = Mathf.Max(0f, LowestFootHeight(rig, groundY));
                if (height >= FADE_HEIGHT)
                {
                    continue;
                }

                float lift01 = height / FADE_HEIGHT;
                float radius = BASE_RADIUS * Mathf.Lerp(1f, SPREAD_AT_FADE, lift01);
                float alpha = Mathf.Lerp(CONTACT_ALPHA, 0f, lift01);

                Vector3 centre = rig.Pelvis.position;
                centre.y = groundY + GROUND_OFFSET;

                var matrix = Matrix4x4.TRS(
                    centre,
                    // Flat on the ground, facing up. The quad is built in the XY
                    // plane, so it is laid down rather than stood up.
                    Quaternion.Euler(90f, 0f, 0f),
                    new Vector3(radius * 2f, radius * 2f, 1f));

                MaterialPropertyBlock block = NextBlock();
                // Black, and the ALPHA carries the strength. The material's
                // texture holds the radial falloff, so the two multiply: soft at
                // the rim, strongest under the foot, and gone in the air.
                block.SetColor(BaseColorId, new Color(0f, 0f, 0f, alpha));
                renderParams.matProps = block;
                Graphics.RenderMesh(renderParams, _quad, 0, matrix);
            }
        }

        /// <summary>
        /// Height of the lower foot above the rig's own probed ground. Falls
        /// back to the pelvis for a rig with no foot sensors — the raptor and
        /// the capsule both have them, but nothing here should assume it.
        /// </summary>
        private static float LowestFootHeight(Systems_FighterRig rig, float groundY)
        {
            float lowest = float.MaxValue;
            if (rig.FootLeftSensor != null)
            {
                lowest = Mathf.Min(lowest, rig.FootLeftSensor.transform.position.y - groundY);
            }
            if (rig.FootRightSensor != null)
            {
                lowest = Mathf.Min(lowest, rig.FootRightSensor.transform.position.y - groundY);
            }
            if (lowest == float.MaxValue)
            {
                // Half the pelvis height is roughly where a foot would be, and
                // "roughly" is the right precision for a blob.
                lowest = (rig.Pelvis.position.y - groundY) * 0.5f;
            }
            return lowest;
        }

        /// <summary>
        /// One property block PER DRAW, pooled and grown once.
        /// <see cref="RenderParams"/> holds a REFERENCE to its matProps and the
        /// draws are not submitted until the frame renders, so a single block
        /// rewritten between calls would give every blob in the ring the darkness
        /// of the last one written.
        /// </summary>
        private MaterialPropertyBlock NextBlock()
        {
            if (_blocksUsed == _blocks.Count)
            {
                _blocks.Add(new MaterialPropertyBlock());
            }
            return _blocks[_blocksUsed++];
        }

        /// <summary>
        /// A unit quad centred on the origin. Two triangles is the entire cost
        /// of this system's geometry, per fighter, per frame.
        /// </summary>
        private static Mesh BuildQuad()
        {
            var mesh = new Mesh { name = "BlobShadowQuad" };
            mesh.SetVertices(new List<Vector3>
            {
                new(-0.5f, -0.5f, 0f),
                new(0.5f, -0.5f, 0f),
                new(0.5f, 0.5f, 0f),
                new(-0.5f, 0.5f, 0f)
            });
            mesh.SetUVs(0, new List<Vector2>
            {
                new(0f, 0f), new(1f, 0f), new(1f, 1f), new(0f, 1f)
            });
            mesh.SetTriangles(new[] { 0, 2, 1, 0, 3, 2 }, 0);
            mesh.RecalculateNormals();
            mesh.RecalculateBounds();
            return mesh;
        }
    }
}
