using UnityEngine;

namespace PoBox
{
    /// <summary>
    /// Footsteps. Until now the fighters walked in total silence: the only
    /// body sounds in the ring were the fall thud and the impulse-scaled scuff,
    /// both of which fire when someone goes DOWN. A race whose whole subject is
    /// whether a policy alternates its feet had no sound for a foot landing.
    ///
    /// It listens to <see cref="Sensor_GroundContact"/> — the same flags the
    /// reward function is scored on — so what you hear is literally what the
    /// trainer counted. A brain that shuffles both feet together sounds like
    /// one; a brain that alternates sounds like walking. That is the point:
    /// alternation is the shipping criterion for the walk race, and this is the
    /// first time it has been audible.
    ///
    /// WHY POLLED RATHER THAN AN EVENT ON THE SENSOR. The sensor is on the
    /// training path — it runs sixteen times per scene at 50 Hz with no
    /// presentation layer attached — and adding an event to it would put a
    /// delegate invocation in the hot loop of every training scene for a sound
    /// no training scene plays. Reading its public flag from here costs the
    /// contest scene two bools per fighter per step and costs training nothing.
    ///
    /// THE LANDING SPEED IS SAMPLED ONE STEP EARLY, on purpose. By the time
    /// contact is reported the solver has already taken the foot's downward
    /// velocity away, so reading it at the moment of landing reports roughly
    /// zero for every step and every footfall plays at the same level. The
    /// previous step's speed is what the foot actually arrived at.
    ///
    /// TWO SURFACES. The balance ring is a canvas over a platform and the walk
    /// race is concrete: a fighter whose ground is the ring floor gets the soft
    /// set, everything else gets the hard set. Picked per FIGHTER rather than
    /// per scene, because <see cref="Systems_ContestSpawner"/> can put a ring
    /// and a floor in the same scene and nothing here should have to know which
    /// scene it is in.
    ///
    /// Created at runtime by <see cref="Systems_ContestSpawner"/> and attaches
    /// nothing to the fighters, so no prefab and no training scene carries it.
    /// Test-scene harness only.
    /// </summary>
    public sealed class Systems_Footsteps : MonoBehaviour
    {
        /// <summary>
        /// Minimum gap between two steps on the SAME foot. The ground flag is a
        /// statement about one physics step, and a foot rolling onto its toe can
        /// break and remake contact within a few steps of each other — without
        /// this, one stride plays as a stutter of three.
        /// </summary>
        private const float PER_FOOT_COOLDOWN = 0.18f;

        /// <summary>
        /// Downward speed below which a landing is not a step. A standing
        /// fighter's feet trade tiny contacts with the floor continuously; this
        /// is what keeps a fighter who is doing nothing from tapping.
        /// </summary>
        private const float MIN_LANDING_SPEED = 0.35f;

        /// <summary>Speed treated as "as hard as a step gets" for scaling.</summary>
        private const float FULL_LANDING_SPEED = 2.6f;

        /// <summary>Voices for footfalls. Eight fighters can land together.</summary>
        private const int AUDIO_VOICES = 6;

        /// <summary>
        /// How far above <see cref="Systems_ContestSpawner.RING_FLOOR_Y"/> a
        /// fighter's probed ground has to be to count as standing on the canvas.
        /// Generous, because GroundY is a raycast result and the platform's
        /// collider top is not exactly its authored height.
        /// </summary>
        private const float CANVAS_GROUND_EPSILON = 0.25f;

        /// <summary>One foot's history. Two per fighter.</summary>
        private struct Foot
        {
            public Sensor_GroundContact sensor;
            public Rigidbody body;
            public bool wasGrounded;
            public float previousDownSpeed;
            public float cooldown;
            public bool onCanvas;
        }

        private Foot[] _feet;
        private AudioSource[] _voices;
        private int _nextVoice;
        private Systems_SpectatorKit _kit;

        private void Start()
        {
            Systems_FighterRig[] rigs = FindObjectsByType<Systems_FighterRig>(FindObjectsSortMode.InstanceID);
            if (rigs.Length == 0)
            {
                return;
            }
            _kit = Systems_SpectatorKit.Load();
            if (_kit == null || !HasAnyClips())
            {
                // Not an error, and deliberately quiet about it: the kit is
                // generated by PoBox/Scene/Build Spectator Kit and a project
                // that has never run it should lose the footsteps, not the
                // contest. Same contract as the joint-stress overlay.
                Debug.LogWarning("Systems_Footsteps: no footstep clips in the spectator kit — " +
                                 "footsteps disabled. Run PoBox/Scene/Build Spectator Kit.");
                return;
            }

            _feet = new Foot[rigs.Length * 2];
            for (int rigIndex = 0; rigIndex < rigs.Length; rigIndex++)
            {
                Systems_FighterRig rig = rigs[rigIndex];
                bool onCanvas = rig.GroundY > Systems_ContestSpawner.RING_FLOOR_Y - CANVAS_GROUND_EPSILON;
                _feet[rigIndex * 2] = BuildFoot(rig.FootLeftSensor, onCanvas);
                _feet[rigIndex * 2 + 1] = BuildFoot(rig.FootRightSensor, onCanvas);
            }
            _voices = BuildVoices();
        }

        private static Foot BuildFoot(Sensor_GroundContact sensor, bool onCanvas)
        {
            return new Foot
            {
                sensor = sensor,
                // The sensor sits on the foot itself on the capsule and on a
                // child of it on the imported characters — the asymmetry
                // Sensor_GroundContact's own header records. Searching upward
                // finds the body in both cases; requiring it on the same object
                // would give the characters no landing speed at all.
                body = sensor != null ? sensor.GetComponentInParent<Rigidbody>() : null,
                wasGrounded = true,
                onCanvas = onCanvas
            };
        }

        private bool HasAnyClips()
        {
            return (_kit.footstepCanvasClips != null && _kit.footstepCanvasClips.Length > 0) ||
                   (_kit.footstepFloorClips != null && _kit.footstepFloorClips.Length > 0);
        }

        /// <summary>
        /// FixedUpdate, because the flag it reads is re-affirmed once per
        /// physics step and a step missed here is a footfall that never plays.
        /// </summary>
        private void FixedUpdate()
        {
            if (_feet == null)
            {
                return;
            }
            float dt = Time.fixedDeltaTime;
            for (int footIndex = 0; footIndex < _feet.Length; footIndex++)
            {
                Foot foot = _feet[footIndex];
                if (foot.sensor == null)
                {
                    continue;
                }
                if (foot.cooldown > 0f)
                {
                    foot.cooldown -= dt;
                }

                bool grounded = foot.sensor.IsGrounded;
                if (grounded && !foot.wasGrounded && foot.cooldown <= 0f &&
                    foot.previousDownSpeed >= MIN_LANDING_SPEED)
                {
                    foot.cooldown = PER_FOOT_COOLDOWN;
                    float strength = Mathf.Clamp01(
                        (foot.previousDownSpeed - MIN_LANDING_SPEED) /
                        (FULL_LANDING_SPEED - MIN_LANDING_SPEED));
                    Play(foot, strength);
                }
                foot.wasGrounded = grounded;
                // Held for the NEXT step to read — see the class remarks.
                foot.previousDownSpeed = foot.body != null
                    ? Mathf.Max(0f, -foot.body.linearVelocity.y)
                    : 0f;
                _feet[footIndex] = foot;
            }
        }

        private void Play(Foot foot, float strength)
        {
            AudioClip[] clips = foot.onCanvas ? _kit.footstepCanvasClips : _kit.footstepFloorClips;
            if (clips == null || clips.Length == 0)
            {
                // One surface's set can be missing without the other's being
                // missing. Fall back rather than going silent on that surface.
                clips = foot.onCanvas ? _kit.footstepFloorClips : _kit.footstepCanvasClips;
            }
            if (clips == null || clips.Length == 0 || _voices == null)
            {
                return;
            }
            AudioClip clip = clips[Random.Range(0, clips.Length)];
            if (clip == null)
            {
                return;
            }

            AudioSource voice = _voices[_nextVoice];
            _nextVoice = (_nextVoice + 1) % _voices.Length;
            voice.transform.position = foot.sensor.transform.position;
            // Random pitch as well as impact-scaled pitch: identical clips on
            // identical feet is the sound of a machine walking, and the ring can
            // hold two copies of the same fighter.
            voice.pitch = Mathf.Lerp(1.12f, 0.9f, strength) * Random.Range(0.96f, 1.04f);
            voice.PlayOneShot(clip, Mathf.Lerp(0.15f, 0.7f, strength));
        }

        /// <summary>
        /// Positioned voices, so a fighter stepping on the far side of the ring
        /// is quieter and off to that side. Built here rather than referenced so
        /// nothing has to be dragged into a scene this system is not placed in —
        /// the same arrangement <see cref="Systems_ImpactFx"/> uses.
        /// </summary>
        private AudioSource[] BuildVoices()
        {
            var voices = new AudioSource[AUDIO_VOICES];
            for (int voiceIndex = 0; voiceIndex < AUDIO_VOICES; voiceIndex++)
            {
                var host = new GameObject("FootstepVoice" + voiceIndex);
                host.transform.SetParent(transform, false);
                var source = host.AddComponent<AudioSource>();
                source.playOnAwake = false;
                source.spatialBlend = 1f;
                source.rolloffMode = AudioRolloffMode.Linear;
                source.minDistance = 1.5f;
                source.maxDistance = 18f;
                voices[voiceIndex] = Systems_AudioMix.Route(source, AudioBus.Foley);
            }
            return voices;
        }
    }
}
